mybatis:
  # 指定 mapper.xml 的位置
  mapper-locations: classpath*:mybatis/mapper/*.xml
  #扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
  type-aliases-package: com.study.homework7.mapper
  configuration:
    #默认开启驼峰命名法，可以不用设置该属性
    map-underscore-to-camel-case: true

#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    hikari:
#      auto-commit: true
#      connection-test-query: SELECT 1
#      connection-timeout: 30000
#      idle-timeout: 180000
#      max-lifetime: 1800000
#      maximum-pool-size: 10
#      minimum-idle: 5
#      pool-name: MyHikariCP
#      primary:
#        password: 123456
#        type: com.zaxxer.hikari.HikariDataSource
#        jdbcUrl: jdbc:mysql://localhost:3306/order1?useUnicode=true&characterEncoding=utf-8&useSSL=false
#        username: root
#      second:
#        password: 123456
#        type: com.zaxxer.hikari.HikariDataSource
#        jdbcUrl: jdbc:mysql://localhost:3306/order2?useUnicode=true&characterEncoding=utf-8&useSSL=false
#        username: root





